import {useState} from 'react';
import {readBuildAreas,checkBuildAreas,areaFitsMap,type BuildArea} from '@/lib/build-areas';
import type {AssetManifest,StateEntity} from '@/lib/wulfram';
export function BuildAreaPanel({raw,entities,width,height,manifest,onPreview,onSave}:{raw?:string;entities:StateEntity[];width:number;height:number;manifest:AssetManifest;onPreview:(a?:BuildArea)=>void;onSave:(areas:BuildArea[])=>void}){
  const [draft,setDraft]=useState<BuildArea>({id:'',name:'Main entrance',kind:'clear',team:'all',x:width/2-100,y:height/2-100,width:200,height:200});
  const [editing,setEditing]=useState(''),[message,setMessage]=useState('');
  const [pointsText,setPointsText]=useState(`${width/2-300}, ${height/2}\n${width/2}, ${height/2+200}\n${width/2+300}, ${height/2}`);
  let areas:BuildArea[]=[],error='';try{areas=readBuildAreas(raw);}catch(e){error=e instanceof Error?e.message:'Invalid build areas.';}
  const change=(next:BuildArea)=>{setDraft(next);onPreview(undefined);};
  const attempt=(fn:()=>void)=>{try{fn();}catch(e){setMessage(e instanceof Error?e.message:'Build-area operation failed.');}};
  const prepare=(id:string):BuildArea=>{
    const a=draft.kind==='corridor'?{...draft,id,points:pointsText.split(/\r?\n/).filter(l=>l.trim()).map(l=>l.trim().split(/[,\s]+/).map(Number) as [number,number])}:{...draft,id};
    return readBuildAreas(JSON.stringify([a]))[0];
  };
  return <details className="build-area-panel"><summary>Build areas and reserved space</summary>
    <p>Blue outlines contain the chosen team’s buildings. Orange outlines reserve empty space for entrances or courts. Checks use conservative building circles, not game collision geometry. Each Apply or Remove is one map Undo step.</p>
    <label>Name<input aria-label="Build area name" value={draft.name} maxLength={120} onChange={e=>change({...draft,name:e.target.value})}/></label>
    <label>Purpose<select aria-label="Build area purpose" value={draft.kind} onChange={e=>{const kind=e.target.value as BuildArea['kind'];const common={id:draft.id,name:draft.name,team:kind==='terrain'?'all' as const:draft.team,width:draft.width};change(kind==='corridor'?{...common,kind,points:[[width/2-300,height/2],[width/2+300,height/2]]}:{...common,kind,x:draft.kind==='corridor'?draft.points[0][0]:draft.x,y:draft.kind==='corridor'?draft.points[0][1]:draft.y,height:draft.kind==='corridor'?200:draft.height});}}><option value="clear">Keep clear</option><option value="boundary">Build inside</option><option value="corridor">Connection corridor</option><option value="terrain">Protect terrain heights</option></select></label>
    <label>Applies to<select aria-label="Build area team" disabled={draft.kind==='terrain'} value={draft.team} onChange={e=>change({...draft,team:e.target.value as BuildArea['team']})}>{['all','1','2','0'].map(t=><option key={t} value={t}>{t==='all'?'All teams':t==='0'?'Neutral':`Team ${t}`}</option>)}</select></label>
    {draft.kind==='corridor'?<><label>Full corridor width<input type="number" aria-label="Build area width" value={draft.width} onChange={e=>change({...draft,width:Number(e.target.value)})}/></label><label>Path points: one X, Y pair per line<textarea aria-label="Corridor points" rows={5} value={pointsText} onChange={e=>{setPointsText(e.target.value);onPreview(undefined);}}/></label><p>Use 2–32 points in world units. The full width reserves a rounded strip along every segment, including bends and endpoints. Magenta outlines show the reservation. This prevents buildings from blocking the corridor; it does not flatten terrain or certify drivability.</p></>:<><div className="district-values">{(['x','y','width','height'] as const).map(k=><label key={k}>{k}<input type="number" aria-label={`Build area ${k}`} value={draft[k]} onChange={e=>change({...draft,[k]:Number(e.target.value)})}/></label>)}</div>{draft.kind==='terrain'&&<p>Green outlines protect terrain heights for every layout and team. Sculpting, stamps and regeneration reject the whole edit if protected heights would change. Border grid vertices are included to preserve interpolation. Painting and building placement remain available. Remove this rule before reshaping this area; Undo restores it.</p>}<p>X/Y locate the lower-coordinate corner; width/height are full extents in world units. Multiple build-inside rectangles all apply, so overlapping rules restrict placement to their intersection.</p></>}
    <div className="district-actions"><button type="button" onClick={()=>attempt(()=>{const a=prepare(editing||'preview');if(!areaFitsMap(a,width,height))throw new Error('Reserved extent extends outside the map. Adjust its points or size before previewing.');onPreview(a);const issues=checkBuildAreas([a],entities,width,height,manifest);setMessage(issues[0]??(a.kind==='terrain'?'Preview fits the map. Apply to protect existing terrain heights.':'Preview fits current buildings. Apply to save this rule.'));})}>Preview build area</button><button type="button" onClick={()=>{onPreview(undefined);setMessage('Preview hidden. Saved rules remain enforced.');}}>Hide area preview</button>
    <button type="button" disabled={!!error} onClick={()=>attempt(()=>{if(editing&&!areas.some(a=>a.id===editing))throw new Error('This area no longer exists. Choose Create another area.');const a=prepare(editing||crypto.randomUUID());const next=editing?areas.map(v=>v.id===editing?a:v):[...areas,a];readBuildAreas(JSON.stringify(next));onSave(next);onPreview(undefined);setEditing('');setMessage('Build area saved. Undo restores it.');})}>Apply build area</button></div>
    {editing&&<button type="button" onClick={()=>{setEditing('');onPreview(undefined);setMessage('Next Apply creates a new area.');}}>Create another area</button>}
    {areas.map(a=><div className="district-actions" key={a.id}><button type="button" onClick={()=>{setEditing(a.id);setDraft(a);if(a.kind==='corridor')setPointsText(a.points.map(p=>p.join(', ')).join('\n'));onPreview(a);}}>{a.name} · {a.kind==='corridor'?'corridor':a.kind==='clear'?'keep clear':a.kind==='terrain'?'protected terrain':'build inside'}</button><button type="button" aria-label={`Remove build area ${a.name}`} onClick={()=>attempt(()=>{onSave(areas.filter(v=>v.id!==a.id));if(editing===a.id)setEditing('');onPreview(undefined);setMessage('Area removed. Buildings unchanged; Undo restores the rule.');})}>Remove area</button></div>)}
    {error&&<p role="alert">{error} Stored metadata retained.</p>}<output aria-live="polite">{message}</output>
  </details>;
}


